### ISSUE TITLE
--track-memory not work

### ISSUE THREAD

**Issue by zhangyangyu** [python/performance#34]
`pyperformance run -m` simply fails:

> [ 1/50] 2to3...
> INFO:root:Running `/tmp/venv/bin/python -u /usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_2to3.py --track-memory --output /tmp/tmpmT5Q1F`
> .ERROR: --worker requires --loops=N or --calibrate-loops
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_2to3.py", line 30, in <module>
>     runner.bench_func('2to3', bench_2to3, command, devnull_out)
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_runner.py", line 485, in bench_func
>     return self._main(task)
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_runner.py", line 420, in _main
>     bench = self._master()
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_runner.py", line 543, in _master
>     bench = Master(self).create_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_master.py", line 221, in create_bench
>     worker_bench, run = self.create_worker_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_master.py", line 120, in create_worker_bench
>     suite = self.create_suite()
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_master.py", line 114, in create_suite
>     suite = self.spawn_worker(0, 0)
>   File "/usr/lib/python2.8/site-packages/perf-1.4-py2.8.egg/perf/_master.py", line 97, in spawn_worker
>     % (cmd[0], exitcode))
> RuntimeError: /tmp/venv/bin/python failed with exit code 1
> ERROR: Benchmark 2to3 failed: Benchmark died
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 132, in run_benchmarks
>     bench = func(cmd_prefix, options)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/__init__.py", line 88, in BM_2to3
>     return run_perf_script(python, options, "2to3")
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 98, in run_perf_script
>     run_command(cmd, hide_stderr=not options.verbose)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 66, in run_command
>     raise RuntimeError("Benchmark died")
> RuntimeError: Benchmark died

pyperformance version is 0.6.1, perf version is 1.4, kernel version is 3.10.0.

**Comment by vstinner** [comment]
It was a perf bug, now fixed by the newly released perf 1.5: http://perf.readthedocs.io/en/latest/changelog.html#version-1-5

I updated perf requirement in commit 655e86fd3587b0182d2b99781fcce1d614ef0525. Can you please try the development version of performance? If it works for you, I can release performance 0.6.1.

**Comment by zhangyangyu** [comment]
Due to environment restrict I can't fully upgrade performance requirements. I just upgrade perf to 1.5 and everything is fine now.  Thanks Victor!

**Comment by zhangyangyu** [comment]
Sorry, I come to the conclusion too early. Other test suites are fine but python_startup and python_startup_no_site still fail with the same error:

> [root@SZX1000328166 tmp]# pyperformance run -b python_startup,python_startup_no_site -m --venv=venv 
> Python benchmark suite 0.6.1
> 
> [1/2] python_startup...
> INFO:root:Running `/tmp/venv/bin/python -u /usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_python_startup.py --track-memory --output /tmp/tmpvFzlu3`
> .ERROR: --worker requires --loops=N or --calibrate-loops
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_python_startup.py", line 29, in <module>
>     runner.bench_command(name, command)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 613, in bench_command
>     return self._main(task)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 428, in _main
>     bench = self._master()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 551, in _master
>     bench = Master(self).create_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 221, in create_bench
>     worker_bench, run = self.create_worker_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 120, in create_worker_bench
>     suite = self.create_suite()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 114, in create_suite
>     suite = self.spawn_worker(0, 0)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 97, in spawn_worker
>     % (cmd[0], exitcode))
> RuntimeError: /tmp/venv/bin/python failed with exit code 1
> ERROR: Benchmark python_startup failed: Benchmark died
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 132, in run_benchmarks
>     bench = func(cmd_prefix, options)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/__init__.py", line 206, in BM_python_startup
>     return run_perf_script(python, options, "python_startup")
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 98, in run_perf_script
>     run_command(cmd, hide_stderr=not options.verbose)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 66, in run_command
>     raise RuntimeError("Benchmark died")
> RuntimeError: Benchmark died
> [2/2] python_startup_no_site...
> INFO:root:Running `/tmp/venv/bin/python -u /usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_python_startup.py --no-site --track-memory --output /tmp/tmpmaRX6M`
> .ERROR: --worker requires --loops=N or --calibrate-loops
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/bm_python_startup.py", line 29, in <module>
>     runner.bench_command(name, command)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 613, in bench_command
>     return self._main(task)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 428, in _main
>     bench = self._master()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_runner.py", line 551, in _master
>     bench = Master(self).create_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 221, in create_bench
>     worker_bench, run = self.create_worker_bench()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 120, in create_worker_bench
>     suite = self.create_suite()
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 114, in create_suite
>     suite = self.spawn_worker(0, 0)
>   File "/usr/lib/python2.8/site-packages/perf-1.5-py2.8.egg/perf/_master.py", line 97, in spawn_worker
>     % (cmd[0], exitcode))
> RuntimeError: /tmp/venv/bin/python failed with exit code 1
> ERROR: Benchmark python_startup_no_site failed: Benchmark died
> Traceback (most recent call last):
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 132, in run_benchmarks
>     bench = func(cmd_prefix, options)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/benchmarks/__init__.py", line 211, in BM_python_startup_no_site
>     extra_args=["--no-site"])
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 98, in run_perf_script
>     run_command(cmd, hide_stderr=not options.verbose)
>   File "/usr/lib/python2.8/site-packages/performance-0.6.1-py2.8.egg/performance/run.py", line 66, in run_command
>     raise RuntimeError("Benchmark died")
> RuntimeError: Benchmark died
> 
> ERROR: No benchmark was run

**Comment by vstinner** [comment]
Oh. I forgot Runner.bench_command(). It has a different implementation, but it had exactly the same bug. I just released perf 1.5.1 which fix --track-memory option for bench_command().

**Comment by zhangyangyu** [comment]
This time every suite is really fine. :+1:

**Comment by vstinner** [comment]
I released performance 0.6.1 which contains the fix.
